@class Account;
@class AddressRecord;
@class Alias;
@class Attachment;
@class Bank;
@class BankAuthorization;
@class BankInfo;
@class Blob;
@class BulkTransfer;
@class Device;
@class DeviceInfo;
@class ExternalAuthorizationDetails;
@class Key;
@class Member;
@class MemberRecoveryOperation;
@class MemberRecoveryOperation_Authorization;
@class Money;
@class Notification;
@class NotifyResult;
@class NSError;
@class OauthBankAuthorization;
@class PagedArray<StandingOrder>;
@class PagedArray<StandingOrderSubmission>;
@class PagedArray<Token>;
@class PagedArray<Transaction>;
@class PagedArray<Transfer>;
@class PrepareTokenResult;
@class Pricing;
@class Profile;
@class ReceiptContact;
@class Signature;
@class StandingOrder;
@class StandingOrderSubmission;
@class Subscriber;
@class TKAccount;
@class TKBalance;
@class TKMember;
@class Token;
@class TokenMember;
@class TokenOperationResult;
@class TokenRequestResult;
@class Transaction;
@class Transfer;
@class TransferEndpoint;
@class TrustedBeneficiary;

typedef NS_ENUM(int32_t, NotifyStatus);

typedef void (^ _Nonnull OnAuthRequired)(ExternalAuthorizationDetails * _Nonnull);
typedef void (^ _Nonnull OnError)(NSError * _Nonnull);
typedef void (^ _Nonnull OnSuccess)(void);
typedef void (^ _Nonnull OnSuccessWithAccount)(Account * _Nonnull);
typedef void (^ _Nonnull OnSuccessWithAccounts)(NSArray<Account *> * _Nonnull);
typedef void (^ _Nonnull OnSuccessWithAddress)(AddressRecord * _Nonnull);
typedef void (^ _Nonnull OnSuccessWithAddresses)(NSArray<AddressRecord *> * _Nonnull);
typedef void (^ _Nonnull OnSuccessWithAliases)(NSArray<Alias *> * _Nonnull);
typedef void (^ _Nonnull OnSuccessWithAttachment)(Attachment * _Nullable);
typedef void (^ _Nonnull OnSuccessWithBankAuthorization)(BankAuthorization * _Nonnull);
typedef void (^ _Nonnull OnSuccessWithBankInfo)(BankInfo * _Nonnull);
typedef void (^ _Nonnull OnSuccessWithBanks)(NSArray<Bank *> * _Nonnull);
typedef void (^ _Nonnull OnSuccessWithBlob)(Blob * _Nullable);
typedef void (^ _Nonnull OnSuccessWithBoolean)(BOOL);
typedef void (^ _Nonnull OnSuccessWithBulkTransfer)(BulkTransfer * _Nonnull);
typedef void (^ _Nonnull OnSuccessWithDeviceInfo)(DeviceInfo * _Nonnull);
typedef void (^ _Nonnull OnSuccessWithKeys)(NSArray<Key *> * _Nonnull);
typedef void (^ _Nonnull OnSuccessWithMember)(Member * _Nonnull);
typedef void (^ _Nonnull OnSuccessWithMemberRecoveryOperation)(MemberRecoveryOperation * _Nonnull);
typedef void (^ _Nonnull OnSuccessWithMemberRecoveryOperationAuthorization)(MemberRecoveryOperation_Authorization * _Nonnull);
typedef void (^ _Nonnull OnSuccessWithMoney)(Money * _Nonnull);
typedef void (^ _Nonnull OnSuccessWithNotification)(Notification * _Nonnull);
typedef void (^ _Nonnull OnSuccessWithNotifications)(PagedArray<Notification *> * _Nonnull);
typedef void (^ _Nonnull OnSuccessWithNotifyStatus)(NotifyStatus);
typedef void (^ _Nonnull OnSuccessWithNotifyResult)(NotifyResult * _Nonnull);
typedef void (^ _Nonnull OnSuccessWithNotifyStatus)(NotifyStatus);
typedef void (^ _Nonnull OnSuccessWithOauthBankAuthorization)(OauthBankAuthorization * _Nonnull);
typedef void (^ _Nonnull OnSuccessWithPairedDevices)(NSArray<Device *> * _Nonnull);
typedef void (^ _Nonnull OnSuccessWithPrepareTokenResult)(PrepareTokenResult * _Nonnull);
typedef void (^ _Nonnull OnSuccessWithProfile)(Profile * _Nonnull);
typedef void (^ _Nonnull OnSuccessWithReceiptContact)(ReceiptContact * _Nonnull);
typedef void (^ _Nonnull OnSuccessWithSignature)(Signature * _Nonnull);
typedef void (^ _Nonnull OnSuccessWithString)(NSString * _Nullable);
typedef void (^ _Nonnull OnSuccessWithStrings)(NSArray<NSString *> * _Nonnull);
typedef void (^ _Nonnull OnSuccessWithStandingOrder)(StandingOrder * _Nonnull);
typedef void (^ _Nonnull OnSuccessWithStandingOrders)(PagedArray<StandingOrder *> * _Nonnull);
typedef void (^ _Nonnull OnSuccessWithStandingOrderSubmission)(StandingOrderSubmission * _Nonnull);
typedef void (^ _Nonnull OnSuccessWithStandingOrderSubmissions)(PagedArray<StandingOrderSubmission *> * _Nonnull);
typedef void (^ _Nonnull OnSuccessWithSubscriber)(Subscriber * _Nonnull);
typedef void (^ _Nonnull OnSuccessWithSubscribers)(NSArray<Subscriber *> * _Nonnull);
typedef void (^ _Nonnull OnSuccessWithTKAccount)(TKAccount * _Nonnull);
typedef void (^ _Nonnull OnSuccessWithTKAccounts)(NSArray<TKAccount *> * _Nonnull);
typedef void (^ _Nonnull OnSuccessWithTKBalance)(TKBalance * _Nonnull);
typedef void (^ _Nonnull OnSuccessWithTKBalances)(NSDictionary<NSString *,TKBalance *> * _Nonnull);
typedef void (^ _Nonnull OnSuccessWithTKMember)(TKMember * _Nonnull);
typedef void (^ _Nonnull OnSuccessWithToken)(Token * _Nonnull);
typedef void (^ _Nonnull OnSuccessWithTokenMember)(TokenMember * _Nullable);
typedef void (^ _Nonnull OnSuccessWithTokenOperationResult)(TokenOperationResult * _Nonnull);
typedef void (^ _Nonnull OnSuccessWithTokenRequestResult)(TokenRequestResult * _Nonnull);
typedef void (^ _Nonnull OnSuccessWithTokens)(PagedArray<Token *> * _Nonnull);
typedef void (^ _Nonnull OnSuccessWithTransaction)(Transaction * _Nonnull);
typedef void (^ _Nonnull OnSuccessWithTransactions)(PagedArray<Transaction *> * _Nonnull);
typedef void (^ _Nonnull OnSuccessWithTransfer)(Transfer * _Nonnull);
typedef void (^ _Nonnull OnSuccessWithTransferEndpoints)(NSArray<TransferEndpoint *> * _Nonnull);
typedef void (^ _Nonnull OnSuccessWithTransfers)(PagedArray<Transfer *> * _Nonnull);
typedef void (^ _Nonnull OnSuccessWithTrustedBeneficiaries)(NSArray<TrustedBeneficiary *> * _Nonnull);
